# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_Author', models.CharField(max_length=20)),
                ('Comment_Text', models.TextField()),
                ('Comment_Like', models.IntegerField()),
                ('Comment_Dislike', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quest_Name', models.CharField(max_length=30)),
                ('Quest_Description', models.TextField()),
                ('Quest_Photo', models.ImageField(upload_to='')),
                ('Quest_Task', models.TextField()),
                ('Quest_Maps', models.TextField()),
                ('Quest_CreateDate', models.DateTimeField(default=datetime.datetime(2016, 10, 31, 3, 2, 2, 361979, tzinfo=utc))),
                ('Quest_Implementation', models.BooleanField(default=False)),
                ('Quest_StartDate', models.DateTimeField()),
                ('Quest_EndDate', models.DateTimeField()),
                ('Quest_Check', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('Uset_SurName', models.CharField(max_length=30)),
                ('User_Login', models.CharField(max_length=20)),
                ('User_Password', models.CharField(max_length=20)),
                ('User_mail', models.EmailField(max_length=254)),
                ('User_Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='Quest_UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_QusetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Quest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_UsersID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.User'),
        ),
    ]
