# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment_QusetID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment_UsersID',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Check',
            new_name='check',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_EndDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Implementation',
            new_name='implementation',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Maps',
            new_name='maps',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_StartDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='Quest_Task',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='Quest_CreateDate',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='Quest_Photo',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='Quest_UserID',
        ),
        migrations.AddField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 13, 19, 55, 345346, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='photo',
            name='questID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Quest'),
        ),
    ]
