# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_auto_20161201_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='questID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Фотографии', to='quest.Quest'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.CharField(max_length=60, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='check',
            field=models.CharField(max_length=30, verbose_name='Слово проверки прохождения квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 9, 11, 57, 469280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(verbose_name='Описание квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончаниея квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='maps',
            field=models.TextField(verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='task',
            field=models.TextField(verbose_name='Задание квеста'),
        ),
    ]
